GET http://127.0.0.1:5000/categories HTTP/1.1

###

GET http://127.0.0.1:5000/questions HTTP/1.1

###

GET http://127.0.0.1:5000/categories/2/questions HTTP/1.1

###

POST http://127.0.0.1:5000/quizzes HTTP/1.1
content-type: application/json

{
    "previous_question": [18, 16, 17],
    "category": "Science"
}


###

POST http://127.0.0.1:5000/questions HTTP/1.1
content-type: application/json

{
    "question": "How do I delete my account?",
    "answer": "press delete",
    "category": "1",
    "difficulty": "3"
}

###

DELETE http://127.0.0.1:5000/questions/31 HTTP/1.1

###

POST http://127.0.0.1:5000/questions HTTP/1.1
content-type: application/json

{
    "searchTerm": "Who invented writing?"
}