GET http://127.0.0.1:5000/categories HTTP/1.1

###

GET http://127.0.0.1:5000/questions?page=1 HTTP/1.1

###

GET http://127.0.0.1:5000/categories/1/questions HTTP/1.1

###

POST http://127.0.0.1:5000/questions HTTP/1.1
content-type: application/json

{
    "question": "Who invented writing?",
    "answer": "The Sumerians",
    "category": "1",
    "difficulty": "2"
}